### ISSUE TITLE
11章 双引号 标点符号错误。

### ISSUE THREAD

**Issue by YangtseSu** [LenKiMo/byte-of-python#17]
11章
建设你想创建一个名为“world”的包，其中还包含着 ”asia“、”africa“等其它子包，同时这些子包都包含了诸如”india“、”madagascar“等模块。
双引号方向反了。

**Comment by LenKiMo** [comment]
Fixed in https://github.com/LenKiMo/byte-of-python/commit/7f9d591d6c06c7be7b22dd303e434b928ee7759c
