### ISSUE TITLE
8.op_exp.md 关于整除//的说法不正确

### ISSUE THREAD

**Issue by Loujibo** [LenKiMo/byte-of-python#19]
原文：

> // （整除）
> 
> x 除以 y 并对结果_向下_取整至**最接近**的整数。
> 13 // 3 输出 4。
> -13 // 3 输出 -5。
> 

并不是最接近的整数
```
print(9/1.81)
4.972375690607735

print(9//1.81)
4.0
```
很明显4.972375690607735最接近的是5而不是4。所以这个地方应该是取整

**Comment by LenKiMo** [comment]
请注意到原文中斜体标注的 **“向下”** 这一限定条件。

**Comment by Loujibo** [comment]
抱歉

**Comment by Loujibo** [comment]
抱歉
